import { prisma, computeFunnel } from "@trendcart/db";
import { Badge, SectionHeading, formatDate } from "../ui";

export const dynamic = "force-dynamic";

const FLOOR = Number(process.env.MIN_ENGAGEMENT_SCORE ?? 10);

const pct = (n: number, d: number): number => (d > 0 ? Math.round((n / d) * 100) : 0);

type Recommendation = { title: string; detail: string; impact: "high" | "medium" | "low" };

const impactTone = (impact: string): "red" | "amber" | "zinc" =>
  impact === "high" ? "red" : impact === "medium" ? "amber" : "zinc";

export default async function InsightsPage() {
  const [funnel, report] = await Promise.all([
    computeFunnel(prisma, { floor: FLOOR }),
    prisma.botMemory.findUnique({ where: { id: "insights" } }),
  ]);

  const basis = (report?.basis ?? null) as { recommendations?: Recommendation[] } | null;
  const recommendations = basis?.recommendations ?? [];

  const c = funnel.candidates;
  const e = funnel.evaluations;
  const r = funnel.replies;
  const llmRejected = e.llmEvaluated - e.wouldReply;

  const stages = [
    { label: "Discovered", value: c.total, drop: null as string | null },
    {
      label: "Evaluated",
      value: c.evaluated,
      drop: `${c.belowFloor} never cleared the engagement floor (${FLOOR}); ${c.dead} deleted`,
    },
    {
      label: "Worth replying",
      value: e.wouldReply,
      drop: `${e.policyGated} cheap policy rejections + ${llmRejected} judged not a fit`,
    },
    {
      label: "Posted",
      value: r.posted,
      drop: `${r.skipped} skipped, ${r.failed} failed, ${r.pendingApproval} awaiting you`,
    },
  ];

  return (
    <div>
      <h1 className="mb-1 text-2xl font-bold">Insights</h1>
      <p className="mb-6 text-sm text-zinc-500">
        Where candidates are won and lost between discovery and a posted reply — plus the bot&apos;s
        daily read on how to increase output. Numbers are all-time and live.
      </p>

      {/* Latest report */}
      {report ? (
        <div className="mb-8 rounded-lg border border-blue-200 bg-blue-50/40 p-4">
          <div className="mb-2 flex items-baseline gap-2">
            <span className="font-medium text-blue-900">The bot&apos;s read</span>
            <span className="text-xs text-blue-700/60">generated {formatDate(report.updatedAt)}</span>
          </div>
          <p className="text-sm text-zinc-700">{report.content.split("\n")[0]}</p>
          {recommendations.length > 0 && (
            <div className="mt-3 space-y-2">
              {recommendations.map((rec, i) => (
                <div key={i} className="flex gap-2 text-sm">
                  <Badge tone={impactTone(rec.impact)}>{rec.impact}</Badge>
                  <div>
                    <span className="font-medium text-zinc-800">{rec.title}.</span>{" "}
                    <span className="text-zinc-600">{rec.detail}</span>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      ) : (
        <div className="mb-8 rounded-lg border border-zinc-200 bg-zinc-50 p-4 text-sm text-zinc-500">
          The daily report is generated by the worker once there&apos;s enough activity — the live
          funnel below is current in the meantime.
        </div>
      )}

      {/* Funnel */}
      <SectionHeading>Funnel</SectionHeading>
      <div className="space-y-2">
        {stages.map((s) => (
          <div key={s.label} className="rounded-lg border border-zinc-200 bg-white p-3">
            <div className="flex items-baseline justify-between">
              <span className="font-medium">{s.label}</span>
              <span className="text-sm text-zinc-500">
                <span className="text-lg font-semibold text-zinc-800">{s.value}</span>
                {" · "}
                {pct(s.value, c.total)}% of discovered
              </span>
            </div>
            <div className="mt-1.5 h-2 w-full overflow-hidden rounded-full bg-zinc-100">
              <div
                className="h-full rounded-full bg-blue-500"
                style={{ width: `${Math.max(pct(s.value, c.total), s.value > 0 ? 1 : 0)}%` }}
              />
            </div>
            {s.drop && <div className="mt-1 text-xs text-zinc-400">lost here: {s.drop}</div>}
          </div>
        ))}
      </div>

      {/* Per category */}
      <SectionHeading>Output by category</SectionHeading>
      <div className="overflow-x-auto rounded-lg border border-zinc-200 bg-white">
        <table className="w-full text-left text-sm">
          <thead className="border-b border-zinc-100 text-xs uppercase text-zinc-400">
            <tr>
              <th className="px-3 py-2">Category</th>
              <th className="px-3 py-2">Worth replying</th>
              <th className="px-3 py-2">Posted</th>
            </tr>
          </thead>
          <tbody>
            {funnel.categories.length === 0 ? (
              <tr>
                <td colSpan={3} className="px-3 py-3 text-zinc-400">
                  No reply-worthy candidates yet.
                </td>
              </tr>
            ) : (
              funnel.categories.map((cat) => (
                <tr key={cat.category} className="border-b border-zinc-50 last:border-0">
                  <td className="px-3 py-2">{cat.category}</td>
                  <td className="px-3 py-2 text-zinc-600">{cat.wouldReply}</td>
                  <td className="px-3 py-2">
                    <span className={cat.posted === 0 ? "text-zinc-300" : "font-medium text-emerald-700"}>
                      {cat.posted}
                    </span>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
      <p className="mt-2 text-xs text-zinc-400">
        Categories with reply-worthy candidates but zero posts are the ones to rework or cut — their
        discovery keywords aren&apos;t landing.
      </p>

      {/* Engagement + skips */}
      <div className="mt-6 grid gap-4 sm:grid-cols-2">
        <div className="rounded-lg border border-zinc-200 bg-white p-4 text-sm">
          <div className="font-medium">Posted-reply engagement</div>
          <div className="mt-1 text-zinc-600">
            {funnel.engagement.likes} likes · {funnel.engagement.replies} replies ·{" "}
            {funnel.engagement.reposts + funnel.engagement.quotes} reposts/quotes across{" "}
            {funnel.engagement.postedCount} posts
          </div>
          <div className="mt-1 text-xs text-zinc-500">
            Your verdicts: 👍 {funnel.operatorRatings.up} · 👎 {funnel.operatorRatings.down}
            {funnel.operatorRatings.withFeedback > 0 &&
              ` · ${funnel.operatorRatings.withFeedback} with notes`}{" "}
            <span className="text-zinc-400">(rate posted replies on the Replies page)</span>
          </div>
        </div>
        <div className="rounded-lg border border-zinc-200 bg-white p-4 text-sm">
          <div className="font-medium">Why replies were skipped</div>
          <div className="mt-1 space-y-0.5 text-xs text-zinc-500">
            {funnel.skipReasons.length === 0 ? (
              <div className="text-zinc-400">none</div>
            ) : (
              funnel.skipReasons.map((s) => (
                <div key={s.reason}>
                  {s.reason} — {s.count}
                </div>
              ))
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
